/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppArticle: typeof import('./src/components/AppArticle.vue')['default']
    Article: typeof import('./src/components/Article.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageTile: typeof import('./src/components/ImageTile.vue')['default']
    ImageTilesGroup: typeof import('./src/components/ImageTilesGroup.vue')['default']
    LanguageToggle: typeof import('./src/components/LanguageToggle.vue')['default']
    MainLayout: typeof import('./src/components/MainLayout.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteFooter: typeof import('./src/components/SiteFooter.vue')['default']
    SiteLogo: typeof import('./src/components/SiteLogo.vue')['default']
    SiteMenu: typeof import('./src/components/SiteMenu.vue')['default']
  }
}
